application:
  name: Realm-Exchange
  project: Realm-Exchange
  publicly_accessible: true
  cloud_region: aws/us-west-2
databases:
- type: postgresql
  version: "11.5"
  name: postgres
routers:
- name: main
  routes:
  - application_name: Realm-Exchange
    paths:
    - /*
